version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - PERSISTENCE=1
    volumes:
      - ./.localstack:/var/lib/localstack
      - ./init.sh:/etc/localstack/init/ready.d/init-aws.sh
